#!/usr/bin/env python3
"""Generate every published number and page from results/.

site/copy.json holds editorial text only. This script joins it with
results/summary.json, results/calibration.json and
results/tfidf_baseline_summary.json and writes:

    site/data.js              RUN + TASKS consumed by site/app.js
    site/decision/<id>.html   one crawlable page per decision
    site/sitemap.xml
    site/robots.txt
    site/index.html           <meta> block between the meta markers

Run with --check to fail when the committed site disagrees with results/,
which is what stops the table from silently drifting from the receipts.
"""
from __future__ import annotations

import html
import json
import re
import sys
from pathlib import Path

try:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
except Exception:  # pragma: no cover
    pass

ROOT = Path(__file__).resolve().parent.parent
RESULTS = ROOT / "results"
SITE = ROOT / "site"

META_START = "<!-- meta:start generated by scripts/build_site.py -->"
META_END = "<!-- meta:end -->"

VERDICT_TEXT = {"replace": "Replace", "mix": "Mix", "dont": "Don't", "neither": "Neither"}


def load(path: Path):
    return json.loads(path.read_text(encoding="utf-8"))


def per_million(cost: float, n: int) -> float:
    return round(cost / n * 1e6, 2)


def e(s) -> str:
    return html.escape(str(s), quote=True)


def pct(x) -> str:
    return f"{x * 100:.1f}%"


def build_tasks(copy, summary, calib, tfidf, errors, modern):
    by_id = {r["task_id"]: r for r in summary}
    tf_by_id = {r["task_id"]: r for r in tfidf}
    mod_by_id = {r["task_id"]: r for r in (modern or {}).get("tasks", [])}
    out = []
    for c in copy["tasks"]:
        tid = c["id"]
        s = by_id[tid]
        t = tf_by_id[tid]
        mc = s["mcnemar"]
        n = s["n"]

        # ns is not an opinion: it is "McNemar did not clear 0.05".
        derived_ns = not mc["significant_0_05"]
        if bool(c["ns"]) != derived_ns:
            raise SystemExit(
                f"{tid}: copy.json says ns={c['ns']} but McNemar p={mc['p_value']:.3g} "
                f"means ns={derived_ns}. Fix the copy, not the number."
            )
        # The reverse direction matters just as much: a row may not claim a winner
        # over Mini when McNemar declined to give it one. "neither" is about all the
        # models at once, so it is allowed to sit on top of an ns row.
        if derived_ns and c["verdict"] in ("replace", "dont"):
            raise SystemExit(
                f"{tid}: copy.json claims verdict={c['verdict']} but McNemar is ns "
                f"(p={mc['p_value']:.3g}). Use \"mix\" or \"neither\"; the badge must not "
                f"crown a winner the test refused to."
            )

        auto = None
        for gate, v in sorted(s["jev_gates"].items()):
            if v["coverage"] >= 0.5 and (auto is None or v["accuracy"] > auto[1]["accuracy"]):
                auto = (gate, v)
        auto_slice = None
        if auto:
            gate, v = auto
            auto_slice = {
                "gate": float(gate),
                "acc": round(v["accuracy"], 4),
                "cov": round(v["coverage"], 4),
                "lift": round(v["accuracy"] - s["jev_acc"], 4),
            }

        # Editorial sentences quote measurements. After a re-run they go stale
        # silently, which is exactly the drift this build is supposed to prevent,
        # so every percentage in the prose must exist somewhere in this task's data.
        known = set()
        for value in (s["jev_acc"], s["mini_acc"], t["acc"]):
            known.add(round(value * 100, 1))
        for gate in s["jev_gates"].values():
            known.add(round(gate["accuracy"] * 100, 1))
            known.add(round(gate["coverage"] * 100, 1))
        known.add(round(abs(s["jev_acc"] - s["mini_acc"]) * 100, 1))
        md = mod_by_id.get(tid)
        if md:
            known.add(round(md["acc"] * 100, 1))
            known.add(round(md["wilson"]["lo"] * 100, 1))
            known.add(round(md["wilson"]["hi"] * 100, 1))
        for gate, v in s["jev_gates"].items():
            known.add(round((v["accuracy"] - s["jev_acc"]) * 100, 1))
        if auto_slice:
            for key in ("acc", "cov", "lift"):
                known.add(round(abs(auto_slice[key]) * 100, 1))
        prof = errors.get(tid, {})
        for arm in prof.values():
            for stats in arm.get("per_class", {}).values():
                for field in ("recall", "missed_rate", "false_positive_rate"):
                    if stats.get(field) is not None:
                        known.add(round(stats[field] * 100, 1))
            for gate in arm.get("recall_at_gate", {}).values():
                for stats in gate.values():
                    if stats.get("recall_on_covered") is not None:
                        known.add(round(stats["recall_on_covered"] * 100, 1))
        for field in ("why", "gate", "rowNote"):
            if not c.get(field):
                continue
            for raw in re.findall(r"(\d+\.?\d*)\s*(?:%|pt)", c[field]):
                # Match at the precision the sentence was written at: "89%" may round
                # a measured 88.8, but "98.6%" must be a measured 98.6, not 98.9.
                decimals = len(raw.split(".")[1]) if "." in raw else 0
                quoted = float(raw)
                if quoted not in {round(k, decimals) for k in known}:
                    raise SystemExit(
                        f"{tid}: copy.json {field} quotes {raw} but no measurement in "
                        f"results/ matches it at that precision. Update the sentence, "
                        f"or the site states a stale number."
                    )

        def versus(key, loser):
            m = t[key]
            if m["p_value"] >= 0.05:
                return "ns"
            return "tfidf" if m["winner"] == "a" else loser

        bins = [
            {"lo": b["lo"], "n": b["n"], "conf": round(b["conf"], 3), "acc": round(b["acc"], 3)}
            for b in calib[tid]["p_chosen"]["bins"]
            if b["n"]
        ]
        out.append({
            "id": tid,
            "n": n,
            "title": c["title"],
            "replaces": c["replaces"],
            "dataset": c["dataset"],
            "labels": c["labels"],
            "verdict": c["verdict"],
            "ns": derived_ns,
            "why": c["why"],
            "gate": c["gate"],
            "goldTier": c["goldTier"],
            "rowNote": c.get("rowNote"),
            "rowNoteKind": c.get("rowNoteKind"),
            "goldNote": c["goldNote"],
            "sourceName": c["sourceName"],
            "sourceUrl": c["sourceUrl"],
            "mirrorUrl": c.get("mirrorUrl"),
            "samplesSha": s["samples_sha256"][:12],
            "schemaSha": s["schema_sha256"][:12],
            "jev": {
                "acc": s["jev_acc"],
                "lo": round(s["jev_wilson"]["lo"], 3),
                "hi": round(s["jev_wilson"]["hi"], 3),
                "p50": round(s["jev_p50_ms"]),
                "p95": round(s["jev_p95_ms"]),
                "conf": round(s["jev_mean_conf"], 3),
                "cost": s["jev_cost"],
                "perM": per_million(s["jev_cost"], n),
            },
            "mini": {
                "acc": s["mini_acc"],
                "lo": round(s["mini_wilson"]["lo"], 3),
                "hi": round(s["mini_wilson"]["hi"], 3),
                "p50": round(s["mini_p50_ms"]),
                "p95": round(s["mini_p95_ms"]),
                "cost": s["mini_cost"],
                "perM": per_million(s["mini_cost"], n),
            },
            "mcnemar": {
                "p": float(f"{mc['p_value']:.3g}"),
                "winner": mc["winner"] if mc["significant_0_05"] else "ns",
                "b": mc["jev_only_correct"],
                "c": mc["mini_only_correct"],
            },
            "tfidf": {
                "acc": t["acc"],
                "lo": round(t["wilson"]["lo"], 3),
                "hi": round(t["wilson"]["hi"], 3),
                "p50us": round(t["predict_p50_ms"] * 1000),
                "trainN": t["train_n"],
                "vsJev": versus("mcnemar_vs_jev", "jev"),
                "vsMini": versus("mcnemar_vs_mini", "mini"),
            },
            "ece": {
                "ece": round(calib[tid]["p_chosen"]["ece"], 3),
                "mce": round(calib[tid]["p_chosen"]["mce"], 3),
                "bins": bins,
            },
            "gates": {
                k: {"cov": v["coverage"], "acc": round(v["accuracy"], 3)}
                for k, v in s["jev_gates"].items()
            },
            "errors": errors.get(tid),
            "modern": ({
                "model": md["model"],
                "acc": md["acc"],
                "lo": round(md["wilson"]["lo"], 3),
                "hi": round(md["wilson"]["hi"], 3),
                "p50": round(md["p50_ms"]),
                "tokens": md["tokens_per_call"],
                "vsJev": ("ns" if md["mcnemar_vs_jev"]["p_value"] >= 0.05
                          else ("modern" if md["mcnemar_vs_jev"]["winner"] == "a" else "jev")),
                "vsMini": ("ns" if md["mcnemar_vs_mini"]["p_value"] >= 0.05
                           else ("modern" if md["mcnemar_vs_mini"]["winner"] == "a" else "mini")),
            } if md else None),
            "autoSlice": auto_slice,
        })
    return out


def render_data_js(run, tasks, site, calls, curve) -> str:
    return (
        "// GENERATED by scripts/build_site.py from results/. Do not edit by hand.\n"
        "// Editorial text lives in site/copy.json; every number here comes from results/.\n"
        f"const SITE = {json.dumps(site, indent=2, ensure_ascii=False)};\n\n"
        f"const CALLS = {json.dumps(calls, indent=2, ensure_ascii=False)};\n\n"
        f"const COST_CURVE = {json.dumps(curve, indent=2, ensure_ascii=False)};\n\n"
        f"const RUN = {json.dumps(run, indent=2, ensure_ascii=False)};\n\n"
        f"const TASKS = {json.dumps(tasks, indent=2, ensure_ascii=False)};\n"
    )


def render_decision_page(t, run, site) -> str:
    slug = t["id"].replace("_", "-")
    url = f"{site['domain']}/decision/{slug}.html"
    # "Replace (ns)" said two opposite things at once. McNemar refusing to crown a
    # winner outranks the editorial verdict, exactly as the table shows it.
    if t["verdict"] == "neither":
        verdict = "Neither"
    elif t["ns"]:
        verdict = "ns"
    else:
        verdict = VERDICT_TEXT[t["verdict"]]
    ns_tag = ""
    title = f"{t['title']}: Jev vs gpt-4o-mini vs TF-IDF | {site['name']}"
    desc = (
        f"{t['title']} on {t['dataset']}, n={t['n']} frozen gold. "
        f"Jev {pct(t['jev']['acc'])}, gpt-4o-mini {pct(t['mini']['acc'])}, "
        f"TF-IDF {pct(t['tfidf']['acc'])}. Verdict: {verdict}. ECE {t['ece']['ece']}."
    )
    gate = t["gates"].get("0.7", {})
    auto = t["autoSlice"]
    lift_pct = auto["lift"] * 100
    lift_txt = f"{'+' if lift_pct >= 0 else ''}{lift_pct:.1f}pt"
    jsonld = {
        "@context": "https://schema.org",
        "@type": "Dataset",
        "name": f"{t['title']} - cheap decision model bake-off",
        "description": desc,
        "url": url,
        "creator": {"@type": "Organization", "name": site["name"], "url": site["domain"]},
        "isBasedOn": t["dataset"],
        "dateModified": run["date"],
        "distribution": [{
            "@type": "DataDownload",
            "encodingFormat": "application/json",
            "contentUrl": f"{site['domain']}/receipts/{t['id']}.json",
        }],
        "variableMeasured": [
            {"@type": "PropertyValue", "name": "jev accuracy", "value": t["jev"]["acc"]},
            {"@type": "PropertyValue", "name": "gpt-4o-mini accuracy", "value": t["mini"]["acc"]},
            {"@type": "PropertyValue", "name": "tfidf accuracy", "value": t["tfidf"]["acc"]},
            {"@type": "PropertyValue", "name": "expected calibration error", "value": t["ece"]["ece"]},
        ],
    }
    train_n = f"{t['tfidf']['trainN']:,}"
    rows = [
        ("Jev " + run["modelJev"], pct(t["jev"]["acc"]),
         f"[{pct(t['jev']['lo'])} - {pct(t['jev']['hi'])}]",
         f"{t['jev']['p50']} ms", f"${t['jev']['perM']}"),
        (run["modelMini"], pct(t["mini"]["acc"]),
         f"[{pct(t['mini']['lo'])} - {pct(t['mini']['hi'])}]",
         f"{t['mini']['p50']} ms", f"${t['mini']['perM']}"),
        (f"TF-IDF + LR (train n={train_n})", pct(t["tfidf"]["acc"]),
         f"[{pct(t['tfidf']['lo'])} - {pct(t['tfidf']['hi'])}]",
         f"{t['tfidf']['p50us']} us", "$0"),
    ]
    if t.get("modern"):
        m = t["modern"]
        rows.insert(2, (m["model"], pct(m["acc"]),
                        f"[{pct(m['lo'])} - {pct(m['hi'])}]",
                        f"{m['p50']} ms", f"{m['tokens']} tok/call"))
    tbody = "\n".join(
        "        <tr>" + "".join(f"<td>{e(c)}</td>" for c in r) + "</tr>" for r in rows
    )
    style = (
        "body{max-width:46rem;margin:0 auto;padding:2rem 1rem;"
        "font:15px/1.6 ui-sans-serif,system-ui,sans-serif;color:#18181b;background:#fafafa}"
        "table{border-collapse:collapse;width:100%;margin:1rem 0}"
        "th,td{border-bottom:1px solid #e4e4e7;padding:.5rem .6rem;text-align:left;"
        "font-variant-numeric:tabular-nums}"
        "th{font-size:11px;text-transform:uppercase;letter-spacing:.06em;color:#71717a}"
        "code{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:13px}"
        "pre{overflow-x:auto}"
        ".verdict{display:inline-block;border:1px solid #d4d4d8;border-radius:999px;"
        "padding:.1rem .6rem;font-size:12px}"
        "a{color:#18181b}"
        "@media (prefers-color-scheme:dark){"
        "body{color:#e4e4e7;background:#09090b}th,td{border-color:#27272a}a{color:#e4e4e7}}"
    )
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{e(title)}</title>
<meta name="description" content="{e(desc)}">
<link rel="canonical" href="{e(url)}">
<link rel="icon" href="../favicon.svg" type="image/svg+xml">
<meta property="og:type" content="article">
<meta property="og:title" content="{e(title)}">
<meta property="og:description" content="{e(desc)}">
<meta property="og:url" content="{e(url)}">
<meta name="twitter:card" content="summary">
<script type="application/ld+json">{json.dumps(jsonld, ensure_ascii=False)}</script>
<style>{style}</style>
</head>
<body>
<p><a href="../index.html">{e(site['name'])}</a> / decision</p>
<h1>{e(t['title'])}</h1>
<p><span class="verdict">{e(verdict)}{ns_tag}</span></p>
<p>{e(t['why'])}</p>
<p><strong>Replaces:</strong> {e(t['replaces'])}<br>
<strong>Gold:</strong> <a href="{e(t['sourceUrl'])}" rel="noopener">{e(t['sourceName'])}</a>
{' via <a href="' + e(t['mirrorUrl']) + '" rel="noopener">a CC0 mirror</a>' if t.get('mirrorUrl') else ''}
- {e(t['dataset'])}, n={t['n']}, seed={run['seed']}<br>
<strong>Labels:</strong> <code>{e(t['labels'])}</code></p>
<table>
  <thead><tr><th>Model</th><th>Accuracy</th><th>95% CI</th><th>p50</th><th>$/1M decisions</th></tr></thead>
  <tbody>
{tbody}
  </tbody>
</table>
<p><strong>McNemar Jev vs Mini:</strong> {e(t['mcnemar']['winner'])}, p={e(t['mcnemar']['p'])}
({t['mcnemar']['b']} Jev-only correct, {t['mcnemar']['c']} Mini-only correct).
<strong>TF-IDF vs Jev:</strong> {e(t['tfidf']['vsJev'])}.</p>
<h2>Quit line</h2>
<p>{e(t['gate'])}</p>
<p><strong>Auto slice:</strong> at Jev confidence &ge; {auto['gate']},
{pct(auto['acc'])} accurate on {pct(auto['cov'])} of traffic, which is
{lift_txt} against {pct(t['jev']['acc'])} ungated. That threshold is the strongest
one still covering at least half the traffic, picked by rule from the measured gates.</p>
<p><strong>Calibration:</strong> ECE {t['ece']['ece']} (max bin gap {t['ece']['mce']}).
ECE says whether the confidence can be read as a probability. It does not say whether
gating helps: thresholding only needs the model to rank its own answers, so a badly
calibrated task can still gate well. High ECE costs you the right to quote the number,
not the right to threshold on it.</p>
<h2>Verify this</h2>
<p>Frozen samples <code>{e(t['samplesSha'])}</code>, schema <code>{e(t['schemaSha'])}</code>.
Every call is stored with its request, response and SHA-256 in
<a href="../receipts/{e(t['id'])}.json">receipts/{e(t['id'])}.json</a>.</p>
<pre><code>git clone {e(site['repo'])}
python3 scripts/verify_run.py   # recounts this table from the receipts, no API key
python3 scripts/run_eval.py     # hits the APIs again with your own keys</code></pre>
<p>Independent bench, not affiliated with TypeSafe AI. Public gold labels, n={t['n']},
not a procurement study. <a href="../index.html">All {run['tasks']} decisions</a> &middot;
<a href="{e(site['repo'])}">source and data</a> &middot;
<a href="mailto:{e(site['contact'])}">{e(site['contact'])}</a></p>
</body>
</html>
"""


def render_sitemap(tasks, site, run) -> str:
    urls = [f"{site['domain']}/", f"{site['domain']}/terms.html", f"{site['domain']}/privacy.html"]
    urls += [f"{site['domain']}/decision/{t['id'].replace('_', '-')}.html" for t in tasks]
    body = "\n".join(
        f"  <url><loc>{u}</loc><lastmod>{run['date']}</lastmod></url>" for u in urls
    )
    return ('<?xml version="1.0" encoding="UTF-8"?>\n'
            '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
            f"{body}\n</urlset>\n")


def render_404(site, run, tasks) -> str:
    """GitHub serves its own generic 404 otherwise, which reads as a dead project."""
    links = "\n".join(
        f'    <li><a href="/decision/{t["id"].replace("_", "-")}.html">{e(t["title"])}</a></li>'
        for t in tasks)
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Not found - {e(site['name'])}</title>
<meta name="robots" content="noindex">
<link rel="icon" href="/favicon.svg" type="image/svg+xml">
<style>
body{{max-width:44rem;margin:0 auto;padding:3rem 1rem;font:15px/1.6 ui-sans-serif,system-ui,sans-serif;color:#18181b;background:#fafafa}}
h1{{font-size:1.5rem;margin:0 0 .5rem}}
ul{{padding-left:1.1rem}}
li{{margin:.15rem 0}}
a{{color:#18181b}}
.muted{{color:#71717a;font-size:13px}}
@media (prefers-color-scheme:dark){{body{{color:#e4e4e7;background:#09090b}}a{{color:#e4e4e7}}}}
</style>
</head>
<body>
<h1>That page does not exist</h1>
<p>Nothing is broken; this URL just is not one of ours. The bench has
{run['tasks']} decisions, each on its own page:</p>
<ul>
{links}
</ul>
<p><a href="/">All {run['tasks']} decisions in one table</a> &middot;
<a href="{e(site['repo'])}">Source and data</a></p>
<p class="muted">Independent bench. Not affiliated with TypeSafe AI.</p>
</body>
</html>
"""


def render_robots(site) -> str:
    return f"User-agent: *\nAllow: /\n\nSitemap: {site['domain']}/sitemap.xml\n"


def render_index_meta(site, run, tasks) -> str:
    desc = site["description"]
    jsonld = {
        "@context": "https://schema.org",
        "@type": "Dataset",
        "name": f"{site['name']} - cheap decision model bake-off",
        "description": desc,
        "url": site["domain"] + "/",
        "creator": {"@type": "Organization", "name": site["name"], "url": site["domain"]},
        "dateModified": run["date"],
        "measurementTechnique": "Wilson 95% CI, McNemar paired test, expected calibration error",
        "hasPart": [
            {"@type": "Dataset",
             "name": t["title"],
             "url": f"{site['domain']}/decision/{t['id'].replace('_', '-')}.html"}
            for t in tasks
        ],
    }
    return "\n".join([
        META_START,
        '  <link rel="icon" href="/favicon.svg" type="image/svg+xml">',
        f'  <meta name="description" content="{e(desc)}">',
        f'  <link rel="canonical" href="{e(site["domain"])}/">',
        '  <meta property="og:type" content="website">',
        f'  <meta property="og:title" content="{e(site["name"])} - {e(site["tagline"])}">',
        f'  <meta property="og:description" content="{e(desc)}">',
        f'  <meta property="og:url" content="{e(site["domain"])}/">',
        '  <meta name="twitter:card" content="summary">',
        f'  <script type="application/ld+json">{json.dumps(jsonld, ensure_ascii=False)}</script>',
        "  " + META_END,
    ])


def write(path: Path, content: str, check: bool, drift: list) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    current = path.read_text(encoding="utf-8") if path.exists() else None
    if current == content:
        return
    rel = path.relative_to(ROOT).as_posix()
    if check:
        drift.append(rel)
    else:
        # Always LF: a Windows build and a Linux build must produce identical bytes,
        # otherwise --check flags drift on every platform switch.
        path.write_text(content, encoding="utf-8", newline="\n")
        print("wrote", rel)


def main() -> None:
    check = "--check" in sys.argv
    copy = load(SITE / "copy.json")
    site = copy["site"]
    summary = load(RESULTS / "summary.json")
    calib = load(RESULTS / "calibration.json")
    tfidf = load(RESULTS / "tfidf_baseline_summary.json")
    errors = load(RESULTS / "error_profile.json")
    modern_path = RESULTS / "modern_baseline.json"
    modern = load(modern_path) if modern_path.exists() else None
    manifest = load(RESULTS / "manifest.json")
    curve_path = RESULTS / "cost_curve.json"
    curve = load(curve_path) if curve_path.exists() else None

    tasks = build_tasks(copy, summary, calib, tfidf, errors, modern)
    # Tasks may differ in size. Prompt injection only has 662 rows in existence, so
    # freezing 500 would leave nothing to train the classical baseline on. The site
    # shows each task's own n instead of claiming one number for all of them.
    sizes = sorted({row["n"] for row in summary})
    counts = {}
    for row in summary:
        counts[row["n"]] = counts.get(row["n"], 0) + 1
    n = max(counts, key=counts.get)

    run = {
        "date": manifest["finished_utc"][:10],
        "runId": manifest["run_id"],
        "modelJev": "jev-1.13.0",
        "modelMini": "gpt-4o-mini-2024-07-18",
        "n": n,
        "nMin": sizes[0],
        "nMax": sizes[-1],
        "seed": manifest["seed"],
        "tasks": len(tasks),
        "note": (f"Frozen samples (seed={manifest['seed']}, n={sizes[0]}-{sizes[-1]} per task). "
                 "Wilson 95% CI on accuracy. "
                 "McNemar on paired errors. Full receipts in results/receipts/. "
                 "APIs do not sign responses."),
    }

    modern_name = next((t["modern"]["model"] for t in tasks if t.get("modern")), None)
    site["description"] = site["descriptionTemplate"].format(
        tasks=len(tasks), modern=modern_name or "no current model column",
        nmin=sizes[0], nmax=sizes[-1])

    drift: list = []
    write(SITE / "data.js", render_data_js(run, tasks, site, copy["calls"], curve), check, drift)
    for t in tasks:
        slug = t["id"].replace("_", "-")
        write(SITE / "decision" / f"{slug}.html", render_decision_page(t, run, site), check, drift)
    write(SITE / "sitemap.xml", render_sitemap(tasks, site, run), check, drift)
    write(SITE / "robots.txt", render_robots(site), check, drift)
    write(SITE / "404.html", render_404(site, run, tasks), check, drift)

    index = SITE / "index.html"
    src = index.read_text(encoding="utf-8")
    if META_START in src and META_END in src:
        head, rest = src.split(META_START, 1)
        _, tail = rest.split(META_END, 1)
        write(index, head + render_index_meta(site, run, tasks) + tail, check, drift)
    else:
        print("WARN index.html has no meta markers; skipping meta injection")

    if check and drift:
        print("STALE, these files disagree with results/:")
        for d in drift:
            print("  ", d)
        print("Run: python3 scripts/build_site.py")
        raise SystemExit(1)
    print("site is in sync with results/" if check else "build complete")


if __name__ == "__main__":
    main()
