#!/usr/bin/env python3
"""Generate every published number and page from results/.

site/copy.json holds editorial text only. This script joins it with
results/summary.json, results/calibration.json and
results/tfidf_baseline_summary.json and writes:

    site/data.js              RUN + TASKS consumed by site/app.js
    site/decision/<id>.html   one crawlable page per decision
    site/sitemap.xml
    site/robots.txt
    site/index.html           <meta> block between the meta markers

Run with --check to fail when the committed site disagrees with results/,
which is what stops the table from silently drifting from the receipts.
"""
from __future__ import annotations

import hashlib
import html
import json
import re
import sys
from datetime import datetime, timedelta
from pathlib import Path

try:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
except Exception:  # pragma: no cover
    pass

ROOT = Path(__file__).resolve().parent.parent
RESULTS = ROOT / "results"
RECEIPTS = RESULTS / "receipts"
DATA = ROOT / "data"
SITE = ROOT / "site"

# Two tasks whose receipts are further apart than this came from separate
# invocations of run_eval.py. Inside one invocation the gap is seconds.
RUN_GAP = timedelta(minutes=10)

META_START = "<!-- meta:start generated by scripts/build_site.py -->"
META_END = "<!-- meta:end -->"

VERDICT_TEXT = {"replace": "Replace", "mix": "Mix", "dont": "Don't", "neither": "Neither"}


def load(path: Path):
    return json.loads(path.read_text(encoding="utf-8"))


def per_million(cost: float, n: int) -> float:
    return round(cost / n * 1e6, 2)


def e(s) -> str:
    return html.escape(str(s), quote=True)


def pct(x) -> str:
    return f"{x * 100:.1f}%"


def holm(pvalues: dict) -> dict:
    """Holm-Bonferroni adjusted p-values for one family of tests.

    Eleven McNemar tests at 0.05 each will crown winners by chance. Holm controls
    the family-wise error rate without Bonferroni's full conservatism. Applied
    separately to each comparison family, never across them.
    """
    order = sorted(pvalues.items(), key=lambda kv: kv[1])
    m = len(order)
    adjusted, running = {}, 0.0
    for i, (key, pv) in enumerate(order):
        running = max(running, min(1.0, (m - i) * pv))
        adjusted[key] = running
    return adjusted


def build_tasks(copy, summary, calib, tfidf, errors, modern, gatefile, windows):
    by_id = {r["task_id"]: r for r in summary}
    tf_by_id = {r["task_id"]: r for r in tfidf}
    mod_by_id = {r["task_id"]: r for r in (modern or {}).get("tasks", [])}
    # One Holm family per comparison: Jev vs Mini, TF-IDF vs Jev, current model vs Jev.
    holm_mini = holm({r["task_id"]: r["mcnemar"]["p_value"] for r in summary})
    holm_tfidf = holm({r["task_id"]: r["mcnemar_vs_jev"]["p_value"] for r in tfidf})
    holm_modern = holm({r["task_id"]: r["mcnemar_vs_jev"]["p_value"]
                        for r in (modern or {}).get("tasks", [])})
    # The "vs 4o-mini" columns are families of eleven tests too. They used to be
    # read at the raw 0.05, which is the same mistake the Jev columns had.
    holm_tfidf_mini = holm({r["task_id"]: r["mcnemar_vs_mini"]["p_value"] for r in tfidf})
    holm_modern_mini = holm({r["task_id"]: r["mcnemar_vs_mini"]["p_value"]
                             for r in (modern or {}).get("tasks", [])})
    out = []
    for c in copy["tasks"]:
        tid = c["id"]
        s = by_id[tid]
        t = tf_by_id[tid]
        mc = s["mcnemar"]
        n = s["n"]
        # One score for gating and calibration. summary.json's jev_gates thresholded
        # on 'confidence' while ECE used 'p_chosen'; gates.json uses p_chosen for both.
        gtab = gatefile[tid]["gates"]
        gcv = gatefile[tid]["cross_validated"]

        # ns is not an opinion: it is "McNemar did not clear 0.05 after Holm
        # correction across all eleven Jev-vs-Mini tests". Uncorrected, two rows
        # (offensive, news) looked significant that do not survive the family.
        p_holm = holm_mini[tid]
        derived_ns = p_holm >= 0.05
        if bool(c["ns"]) != derived_ns:
            raise SystemExit(
                f"{tid}: copy.json says ns={c['ns']} but Holm-adjusted p={p_holm:.3g} "
                f"(raw {mc['p_value']:.3g}) means ns={derived_ns}. Fix the copy, not the number."
            )
        # The reverse direction matters just as much: a row may not claim a winner
        # over Mini when McNemar declined to give it one. "neither" is about all the
        # models at once, so it is allowed to sit on top of an ns row.
        if derived_ns and c["verdict"] in ("replace", "dont"):
            raise SystemExit(
                f"{tid}: copy.json claims verdict={c['verdict']} but McNemar is ns "
                f"after Holm (p={p_holm:.3g}, raw {mc['p_value']:.3g}). Use \"mix\" or \"neither\"; the badge must not "
                f"crown a winner the test refused to."
            )

        auto = None
        for gate, v in sorted(gtab.items()):
            if (v["accuracy"] is not None and v["coverage"] >= 0.5
                    and (auto is None or v["accuracy"] > auto[1]["accuracy"])):
                auto = (gate, v)
        auto_slice = None
        if auto:
            gate, v = auto
            auto_slice = {
                "gate": float(gate),
                "acc": round(v["accuracy"], 4),
                "cov": round(v["coverage"], 4),
                "lift": round(v["accuracy"] - s["jev_acc"], 4),
                "cvAcc": gcv["accuracy_mean"],
                "cvLo": gcv["accuracy_lo"],
                "cvHi": gcv["accuracy_hi"],
            }

        # Editorial sentences quote measurements. After a re-run they go stale
        # silently, which is exactly the drift this build is supposed to prevent,
        # so every percentage in the prose must exist somewhere in this task's data.
        known = set()
        for value in (s["jev_acc"], s["mini_acc"], t["acc"]):
            known.add(round(value * 100, 1))
        for gate in gtab.values():
            if gate["accuracy"] is None:
                continue
            known.add(round(gate["accuracy"] * 100, 1))
            known.add(round(gate["coverage"] * 100, 1))
        known.add(round(abs(s["jev_acc"] - s["mini_acc"]) * 100, 1))
        md = mod_by_id.get(tid)
        if md:
            known.add(round(md["acc"] * 100, 1))
            known.add(round(md["wilson"]["lo"] * 100, 1))
            known.add(round(md["wilson"]["hi"] * 100, 1))
        for gate, v in gtab.items():
            if v["accuracy"] is None:
                continue
            known.add(round((v["accuracy"] - s["jev_acc"]) * 100, 1))
        if auto_slice:
            for key in ("acc", "cov", "lift"):
                known.add(round(abs(auto_slice[key]) * 100, 1))
        prof = errors.get(tid, {})
        for arm in prof.values():
            for stats in arm.get("per_class", {}).values():
                for field in ("recall", "missed_rate", "false_positive_rate"):
                    if stats.get(field) is not None:
                        known.add(round(stats[field] * 100, 1))
            for gate in arm.get("recall_at_gate", {}).values():
                for stats in gate.values():
                    if stats.get("recall_on_covered") is not None:
                        known.add(round(stats["recall_on_covered"] * 100, 1))
        for field in ("why", "gate", "rowNote"):
            if not c.get(field):
                continue
            for raw in re.findall(r"(\d+\.?\d*)\s*(?:%|pt)", c[field]):
                # Match at the precision the sentence was written at: "89%" may round
                # a measured 88.8, but "98.6%" must be a measured 98.6, not 98.9.
                decimals = len(raw.split(".")[1]) if "." in raw else 0
                quoted = float(raw)
                if quoted not in {round(k, decimals) for k in known}:
                    raise SystemExit(
                        f"{tid}: copy.json {field} quotes {raw} but no measurement in "
                        f"results/ matches it at that precision. Update the sentence, "
                        f"or the site states a stale number."
                    )

        def versus(key, loser):
            m = t[key]
            adj = holm_tfidf[tid] if key == "mcnemar_vs_jev" else holm_tfidf_mini[tid]
            if adj >= 0.05:
                return "ns"
            return "tfidf" if m["winner"] == "a" else loser

        bins = [
            {"lo": b["lo"], "n": b["n"], "conf": round(b["conf"], 3), "acc": round(b["acc"], 3)}
            for b in calib[tid]["p_chosen"]["bins"]
            if b["n"]
        ]
        out.append({
            "id": tid,
            "n": n,
            "title": c["title"],
            "replaces": c["replaces"],
            "dataset": c["dataset"],
            "labels": c["labels"],
            "verdict": c["verdict"],
            "ns": derived_ns,
            "why": c["why"],
            "gate": c["gate"],
            "goldTier": c["goldTier"],
            "rowNote": c.get("rowNote"),
            "rowNoteKind": c.get("rowNoteKind"),
            "goldNote": c["goldNote"],
            "sourceName": c["sourceName"],
            "sourceUrl": c["sourceUrl"],
            "mirrorUrl": c.get("mirrorUrl"),
            "samplesSha": s["samples_sha256"][:12],
            "schemaSha": s["schema_sha256"][:12],
            "jev": {
                "acc": s["jev_acc"],
                "lo": round(s["jev_wilson"]["lo"], 3),
                "hi": round(s["jev_wilson"]["hi"], 3),
                "p50": round(s["jev_p50_ms"]),
                "p95": round(s["jev_p95_ms"]),
                "conf": round(s["jev_mean_conf"], 3),
                "cost": s["jev_cost"],
                "perM": per_million(s["jev_cost"], n),
            },
            "mini": {
                "acc": s["mini_acc"],
                "lo": round(s["mini_wilson"]["lo"], 3),
                "hi": round(s["mini_wilson"]["hi"], 3),
                "p50": round(s["mini_p50_ms"]),
                "p95": round(s["mini_p95_ms"]),
                "cost": s["mini_cost"],
                "perM": per_million(s["mini_cost"], n),
            },
            "mcnemar": {
                "p": float(f"{mc['p_value']:.3g}"),
                "pHolm": float(f"{p_holm:.3g}"),
                "winner": mc["winner"] if not derived_ns else "ns",
                "b": mc["jev_only_correct"],
                "c": mc["mini_only_correct"],
            },
            "tfidf": {
                "acc": t["acc"],
                "lo": round(t["wilson"]["lo"], 3),
                "hi": round(t["wilson"]["hi"], 3),
                # A batched predict() over all rows divided by the row count: a mean
                # per row, not a median, so it is not called p50 anywhere.
                "meanUsBatched": round(t["predict_mean_ms_per_row_batched"] * 1000),
                "trainN": t["train_n"],
                "vsJev": versus("mcnemar_vs_jev", "jev"),
                "vsMini": versus("mcnemar_vs_mini", "mini"),
                "pJev": float(f"{t['mcnemar_vs_jev']['p_value']:.3g}"),
                "pJevHolm": float(f"{holm_tfidf[tid]:.3g}"),
                "pMini": float(f"{t['mcnemar_vs_mini']['p_value']:.3g}"),
                "pMiniHolm": float(f"{holm_tfidf_mini[tid]:.3g}"),
            },
            "run": windows[tid],
            "ece": {
                "ece": round(calib[tid]["p_chosen"]["ece"], 3),
                "mce": round(calib[tid]["p_chosen"]["mce"], 3),
                "bins": bins,
            },
            "gates": {
                k: {"cov": v["coverage"], "acc": round(v["accuracy"], 3)}
                for k, v in gtab.items() if v["accuracy"] is not None
            },
            "errors": errors.get(tid),
            "modern": ({
                "model": md["model"],
                "acc": md["acc"],
                "lo": round(md["wilson"]["lo"], 3),
                "hi": round(md["wilson"]["hi"], 3),
                "p50": round(md["p50_ms"]),
                "tokens": md["tokens_per_call"],
                "vsJev": ("ns" if holm_modern.get(tid, 1.0) >= 0.05
                          else ("modern" if md["mcnemar_vs_jev"]["winner"] == "a" else "jev")),
                "vsMini": ("ns" if holm_modern_mini.get(tid, 1.0) >= 0.05
                           else ("modern" if md["mcnemar_vs_mini"]["winner"] == "a" else "mini")),
                "pJev": float(f"{md['mcnemar_vs_jev']['p_value']:.3g}"),
                "pJevHolm": float(f"{holm_modern[tid]:.3g}"),
                "pMini": float(f"{md['mcnemar_vs_mini']['p_value']:.3g}"),
                "pMiniHolm": float(f"{holm_modern_mini[tid]:.3g}"),
            } if md else None),
            "autoSlice": auto_slice,
        })
    return out



def run_windows(summary) -> tuple[list[dict], dict]:
    """Which invocation of run_eval.py produced each row, read off the receipts.

    summary.json carries a run_id only on rows written after that field existed,
    so counting run ids under-reports. Every receipt has a UTC stamp, and rows
    whose stamps sit within RUN_GAP of each other came from one invocation.
    """
    spans = []
    for row in summary:
        rec = load(RECEIPTS / f"{row['task_id']}.json")
        stamps = [r["utc"] for arm in ("jev", "gpt4o_mini") for r in rec[arm] if r.get("utc")]
        spans.append((min(stamps), max(stamps), row["task_id"]))
    spans.sort()
    runs: list[dict] = []
    for start, end, tid in spans:
        if runs and datetime.fromisoformat(start) - datetime.fromisoformat(runs[-1]["end"]) <= RUN_GAP:
            runs[-1]["end"] = max(runs[-1]["end"], end)
            runs[-1]["tasks"].append(tid)
        else:
            runs.append({"start": start, "end": end, "tasks": [tid]})
    per_task = {}
    for i, r in enumerate(runs, 1):
        r["index"] = i
        for tid in r["tasks"]:
            per_task[tid] = {"index": i, "of": len(runs), "start": r["start"], "end": r["end"]}
    return runs, per_task


GEN_OPEN = "<!-- generated:{name} -->"
GEN_CLOSE = "<!-- /generated:{name} -->"

TIER_LABEL = {"live": "live system", "real": "real text", "research": "academic"}
VERDICT_LABEL = {"replace": "Replace", "dont": "Don't", "mix": "Mix", "neither": "Neither"}


def md_table(header: list[str], rows: list[list[str]]) -> str:
    out = ["| " + " | ".join(header) + " |", "|" + "---|" * len(header)]
    out += ["| " + " | ".join(str(c) for c in r) + " |" for r in rows]
    return "\n".join(out)


def pfmt(x: float) -> str:
    return f"{x:.3g}"


def duplicate_texts() -> dict:
    """Rows in data/<task>.jsonl whose text also appears earlier in the same file."""
    out = {}
    for path in sorted(DATA.glob("*.jsonl")):
        if path.name.endswith(".text.jsonl"):
            continue
        seen, dup = set(), 0
        with path.open(encoding="utf-8") as f:
            for line in f:
                r = json.loads(line)
                key = r.get("text_sha256") or r.get("text")
                if key in seen:
                    dup += 1
                seen.add(key)
        out[path.stem] = dup
    return out


# Rows appended by the top-up branch of prepare_samples.balanced() when a label
# had fewer source rows than the balanced share. Recorded from the frozen run:
# offensive had 240 source rows for one label (10 top-ups), emotion 123 (2).
TOPUP_IDS = {"content_offensive": range(490, 500), "message_emotion": range(498, 500)}


def topup_duplicates(task_id: str, ids) -> int:
    """How many top-up rows repeat a text the first pass had already chosen."""
    earlier, dup = set(), 0
    with (DATA / f"{task_id}.jsonl").open(encoding="utf-8") as f:
        for line in f:
            r = json.loads(line)
            key = r.get("text_sha256") or r.get("text")
            if r["id"] in ids:
                dup += key in earlier
            else:
                earlier.add(key)
    return dup


def readme_blocks(tasks, run, curve, errors, gatefile, modern) -> dict:
    """Every table and numeric sentence in README.md, derived from results/.

    The README used to be typed by hand and drifted three times behind the site
    it describes. Now it is generated between marker comments and --check fails
    when it disagrees with results/, exactly like the site does.
    """
    by = {t["id"]: t for t in tasks}
    n_tasks = len(tasks)
    blocks = {}

    ece_sorted = sorted(tasks, key=lambda t: t["ece"]["ece"])
    blocks["ece-line"] = (
        "**Calibration (ECE on p_chosen, 10 bins, `scripts/calibrate.py`):** "
        + ", ".join(f"{t['title'].lower()} {t['ece']['ece']:.3f}" for t in ece_sorted)
        + ". A quit line is only honest where ECE is low. Do not auto-route on the high ones."
    )

    sizes = {}
    for t in tasks:
        sizes.setdefault(t["n"], []).append(t)
    common = max(sizes, key=lambda k: len(sizes[k]))
    others = ", ".join(f"{t['title'].lower()} (n={t['n']})" for k, ts in sizes.items()
                       if k != common for t in ts)
    heading = f"## Results, seed {run['seed']}, n={common} per task" + (f" except {others}" if others else "")
    rows = []
    for t in tasks:
        mc = t["mcnemar"]
        winner = "ns" if t["ns"] else mc["winner"]
        verdict = "ns" if t["ns"] else VERDICT_LABEL[t["verdict"]]
        if t["ns"] and t["verdict"] == "neither":
            verdict = "ns, Neither"
        rows.append([
            t["title"], t["n"],
            f"{pct(t['jev']['acc'])} [{pct(t['jev']['lo'])}-{pct(t['jev']['hi'])}]",
            pct(t["mini"]["acc"]),
            f"{winner} raw p={pfmt(mc['p'])}, Holm p={pfmt(mc['pHolm'])}",
            f"{t['ece']['ece']:.3f}", verdict,
        ])
    flipped = [t for t in tasks if t["mcnemar"]["p"] < 0.05 <= t["mcnemar"]["pHolm"]]
    blocks["main-table"] = (
        heading + "\n\n"
        f"Wilson 95% CI. McNemar on paired errors, Holm-corrected across the {n_tasks} Jev-vs-Mini\n"
        "tests. `ns` = Holm p >= 0.05, meaning the accuracy gap is noise and neither model should\n"
        "be crowned. "
        + (f"{len(flipped)} row(s) clear the raw 0.05 and not the corrected one: "
           + ", ".join(t["title"].lower() for t in flipped) + "."
           if flipped else "No row changes verdict under the correction.")
        + "\n\n" + md_table(["Decision", "n", "Jev", "Mini", "McNemar", "ECE", "Verdict"], rows)
    )

    # current small model column
    mt = [t for t in tasks if t.get("modern")]
    if mt:
        model = mt[0]["modern"]["model"]
        short = model.rsplit("-", 3)[0] if model.count("-") >= 3 else model
        def cell(v, mine, other):
            return {"ns": "ns", "modern": f"**{short}**"}.get(v, other)
        rows = [[t["title"], pct(t["jev"]["acc"]), pct(t["mini"]["acc"]), pct(t["modern"]["acc"]),
                 cell(t["modern"]["vsJev"], short, "Jev"),
                 cell(t["modern"]["vsMini"], short, "4o-mini")] for t in mt]
        wins = [t for t in mt if t["modern"]["vsJev"] == "jev"]
        losses = [t for t in mt if t["modern"]["vsJev"] == "modern"]
        ties = [t for t in mt if t["modern"]["vsJev"] == "ns"]
        raw_wins = [t for t in mt if t["modern"]["pJev"] < 0.05 <= t["modern"]["pJevHolm"]]
        text = (
            "Fair objection, so here is a current small model on the same frozen samples with the\n"
            f"same prompts (`scripts/run_modern_baseline.py`, model `{model}`). Both `vs` columns are\n"
            f"Holm-corrected within their own family of {len(mt)} tests:\n\n"
            + md_table(["Decision", "Jev", "4o-mini (2024)", f"{short} (2026)", "vs Jev", "vs 4o-mini"], rows)
            + f"\n\n**Jev {len(wins)} win{'s' if len(wins) != 1 else ''}, {len(ties)} ties, "
            f"{len(losses)} loss{'es' if len(losses) != 1 else ''}** against a model two years newer."
        )
        if raw_wins:
            text += (f" {len(raw_wins)} row(s) that beat it at the raw 0.05 ("
                     + ", ".join(t["title"].lower() for t in raw_wins)
                     + ") do not survive the correction.")
        if any(t["id"] == "prompt_injection" for t in losses):
            e = errors["prompt_injection"]
            text += (
                "\nThe loss is prompt injection, and it matters: the 2026 model catches\n"
                f"{pct(e['modern']['per_class']['injection']['recall'])} of injections against Jev's\n"
                f"{pct(e['jev']['per_class']['injection']['recall'])}, at "
                f"{pct(e['modern']['per_class']['injection']['false_positive_rate'])} and "
                f"{pct(e['jev']['per_class']['injection']['false_positive_rate'])} false positives.\n"
                f"It is genuinely better there and still misses "
                f"{pct(e['modern']['per_class']['injection']['missed_rate'])}, so the Neither verdict\n"
                "on that row stands for all three."
            )
        blocks["modern-table"] = text

    # auto slice
    rows, lifts, optimism = [], [], []
    for t in tasks:
        a = t["autoSlice"]
        if not a:
            continue
        rows.append([t["title"], TIER_LABEL[t["goldTier"]], f"{t['ece']['ece']:.3f}",
                     f"{pct(a['acc'])} on {pct(a['cov'])} (>={a['gate']})",
                     f"{a['lift'] * 100:+.1f}pt", pct(a["cvAcc"])])
        lifts.append(a["lift"] > 0)
        optimism.append((a["acc"] - a["cvAcc"]) * 100)
    blocks["gate-table"] = (
        md_table(["Decision", "Gold", "ECE", "Auto slice (gate)", "Lift vs ungated",
                  "Cross-validated"], rows)
        + f"\n\nGating beats not gating on **{sum(lifts)} of {len(lifts)} rows**. "
        "The last column chooses the gate on one random half and scores it on the other, "
        f"400 splits; the optimism of picking and scoring on the same rows is at most "
        f"{max(optimism):.1f}pt here. What a high ECE costs you is the right to quote the "
        "confidence number as a probability, not the right to threshold on it."
    )

    # injection classes
    e = errors["prompt_injection"]
    pi = by["prompt_injection"]
    j, m = e["jev"]["per_class"]["injection"], e["mini"]["per_class"]["injection"]
    g9 = e["jev"]["recall_at_gate"]["0.9"]["injection"]
    blocks["injection-classes"] = (
        f"The prompt-injection row looks fine on accuracy: Jev {pct(pi['jev']['acc'])},\n"
        f"Mini {pct(pi['mini']['acc'])}, tied at raw p={pfmt(pi['mcnemar']['p'])}.\n"
        "Split it by class and the picture changes:\n\n"
        + md_table(["", "Jev", "4o-mini"], [
            ["Injections caught", pct(j["recall"]), pct(m["recall"])],
            ["Injections missed", f"{j['missed']} of {j['n']}", f"{m['missed']} of {m['n']}"],
            ["Legitimate text wrongly blocked", pct(j["false_positive_rate"]), pct(m["false_positive_rate"])],
        ])
        + "\n\nBoth models are biased hard toward letting text through. They almost never block a\n"
        f"legitimate request, and they miss roughly {round(j['missed_rate'] * 10)} injections in ten.\n\n"
        "The quit line does not rescue it either. Raising Jev's threshold from 0.5 to 0.9 moves\n"
        f"injection recall from {pct(j['recall'])} to only\n"
        f"{pct(g9['recall_on_covered'])} on the {g9['covered']} injections it still covers, while coverage falls, so the misses\n"
        "move to a human rather than disappearing. That is a documented exception to this site's\n"
        "own headline, and it stays on the page."
    )

    # hate vs civil
    h, c = by["content_hate"], by["civil_toxicity"]
    def mc_cell(t):
        mc = t["mcnemar"]
        if t["ns"]:
            return f"ns, Holm p={pfmt(mc['pHolm'])}"
        return f"{'Mini' if mc['winner'] == 'mini' else 'Jev'} wins, Holm p={pfmt(mc['pHolm'])}"
    blocks["hate-vs-civil"] = (
        md_table(["", "TweetEval hate", "Civil Comments (CC0)"], [
            ["Jev", pct(h["jev"]["acc"]), pct(c["jev"]["acc"])],
            ["4o-mini", pct(h["mini"]["acc"]), pct(c["mini"]["acc"])],
            ["McNemar", mc_cell(h), mc_cell(c)],
            ["ECE", f"{h['ece']['ece']:.3f}", f"{c['ece']['ece']:.3f}"],
        ])
        + f"\n\nOn TweetEval, Mini wins by {abs(h['mini']['acc'] - h['jev']['acc']) * 100:.1f} points and Jev's\n"
        "confidence is too badly calibrated to gate on. On CC0 gold for the same judgement the\n"
        "models tie and the confidence becomes usable. So the Don't was mostly a fact about that\n"
        "dataset. Both rows stay up: deleting the inconvenient one would be the opposite of the\n"
        "point."
    )

    # cfpb cost sentence
    cf = by["cfpb_queue_route"]
    chars = 0
    rows_n = 0
    with (DATA / "cfpb_queue_route.jsonl").open(encoding="utf-8") as f:
        for line in f:
            chars += len(json.loads(line)["text"])
            rows_n += 1
    mean_chars = round(chars / rows_n)
    blocks["cfpb-cost"] = (
        "**Consumer complaint routing is the only production decision here.** The CFPB runs it\n"
        "live, the consumer writes the narrative and picks the product, and the complaint is\n"
        "routed to the company on that basis. Its narratives are the longest on the board and clear the\n"
        f"cost crossover: at about {mean_chars:,} characters per narrative, roughly {round(mean_chars / 4):,} tokens, Jev costs\n"
        f"${cf['jev']['perM']:.2f} per million decisions against ${cf['mini']['perM']:.2f}\n"
        "for 4o-mini. Text comes from a CC0 mirror; the gold label is joined from the Bureau's\n"
        "own export on Complaint ID, and 31,990 of 32,000 candidate rows agreed with zero\n"
        "disagreements. Product is chosen by the person filing, not an expert annotator."
    )

    # tfidf
    def tf_cell(v, other):
        return {"ns": "ns", "tfidf": "TF-IDF wins"}.get(v, f"{other} wins")
    rows = [[t["title"], pct(t["tfidf"]["acc"]), tf_cell(t["tfidf"]["vsJev"], "Jev"),
             tf_cell(t["tfidf"]["vsMini"], "Mini")] for t in tasks]
    both = [t for t in tasks if t["tfidf"]["vsJev"] == "tfidf" and t["tfidf"]["vsMini"] == "tfidf"]
    blocks["tfidf-table"] = (
        "**TF-IDF + logistic regression** on the official train leftover, never touching the\n"
        "frozen samples (`scripts/run_tfidf_baseline.py`). Both columns Holm-corrected within\n"
        f"their family of {n_tasks}:\n\n"
        + md_table(["Decision", "TF-IDF", "vs Jev", "vs Mini"], rows)
        + "\n\nIf you have labels, skip both APIs on "
        + (", ".join(t["title"].lower() for t in both) if both else "no row here")
        + ". Predicts in microseconds for $0."
    )

    # cost curve
    pts = curve["points"]
    rows = [[round(p["mean_content_tokens"]), round(p["mini_prompt_tokens"]),
             round(p["mini_cached_tokens"]), f"${p['jev_per_million']}", f"${p['mini_per_million']}",
             p["cheaper"]] for p in pts]
    cheaper = [t for t in tasks if t["jev"]["perM"] < t["mini"]["perM"]]
    x = curve["crossover"]
    ratio = curve["prices_usd_per_million"]["mini"]["input"] / curve["prices_usd_per_million"]["jev"]["input"]
    blocks["cost-curve"] = (
        f"Jev bills about **{curve['jev_fixed_overhead_tokens']} input tokens before your content**,\n"
        f"then charges {ratio:.1f}x less per token than 4o-mini and nothing for output. So the question\n"
        "is not which model is cheaper, it is how long your input is\n"
        f"(`scripts/cost_curve.py`, {curve['samples_per_point']} calls per point, same document to both):\n\n"
        + md_table(["Content tokens", "Mini prompt tokens", "of which cached", "Jev $/1M",
                    "4o-mini $/1M", "Cheaper"], rows)
        + "\n\n"
        + (f"Crossover: Jev becomes the cheaper option above roughly **{x['content_tokens']} tokens of "
           f"actual input**, about {x['content_tokens'] * 4} characters. " if x else
           "No crossover inside the measured range. ")
        + f"That is after removing the ~{round(curve['mini_overhead_tokens'])}-token system prompt "
        "4o-mini adds to every call; an earlier version of this page counted that prompt as content "
        "and reported 65. Mini prompt tokens the API reports as cached are priced at the cached "
        f"rate (${curve['prices_usd_per_million']['mini']['cached_input']}/M); only the longest point "
        "had any. Measured on the rows themselves, Jev is the cheaper API on "
        f"**{len(cheaper)} of {n_tasks}**: "
        + ", ".join(t["title"].lower() for t in cheaper)
        + ". The short-text rows go to Mini. Receipts in `results/receipts/cost_curve.json`."
    )

    sms = by["sms_spam"]
    blocks["latency"] = (
        f"**Latency** p50 was {sms['jev']['p50']}ms Jev against\n"
        f"{sms['mini']['p50']}ms Mini on SMS in this run, including client\n"
        "round-trip."
    )

    # limits
    dups = duplicate_texts()
    bugged = {tid: topup_duplicates(tid, ids) for tid, ids in TOPUP_IDS.items()}
    dup_line = ", ".join(f"{by[k]['title'].lower()} {v}" for k, v in dups.items() if v)
    blocks["limits"] = (
        "- **Balanced samples, not production mix.** Every task is sampled with equal counts per\n"
        "  label. That makes accuracy comparable across models but it is not the share of each\n"
        "  label in real traffic, so a gate's coverage and accuracy here will not be the ones you\n"
        "  see in production. A spam gate at 50% spam behaves differently from one at 3%.\n"
        "- **Some frozen rows repeat a text.** Rows whose text already appears earlier in the same\n"
        f"  sample: {dup_line}. SMS spam and CFPB duplicates are in the source data. "
        f"{bugged['content_offensive']} of the offensive rows and {bugged['message_emotion']} of the emotion rows\n"
        "  were drawn twice by a top-up bug in `prepare_samples.py` (it dropped the wrong index\n"
        "  before refilling an unbalanced label; fixed, see `results/code_patches.json`). The\n"
        "  frozen samples and receipts are kept as run; a re-run on a corrected sample would move\n"
        f"  those two rows by at most {bugged['content_offensive'] / by['content_offensive']['n'] * 100:.1f}pt and "
        f"{bugged['message_emotion'] / by['message_emotion']['n'] * 100:.1f}pt.\n"
        "- **The auto-slice gate is chosen and scored on the same rows.** That flatters it in\n"
        "  principle. Measured: choosing the gate on one half and scoring it on the other, over\n"
        f"  400 random splits, moves the result by at most {max(optimism):.1f}pt on any row, because there\n"
        "  are only five candidate gates and the pick is stable. `results/gates.json` carries both\n"
        "  numbers.\n"
        f"- **{n_tasks} comparisons at once.** Significance is Holm-corrected within each comparison\n"
        "  family. "
        + (f"{len(flipped)} row(s) that looked like wins for Jev over 4o-mini ("
           + ", ".join(t["title"].lower() for t in flipped)
           + ") do not survive the correction and are shown as ties.\n" if flipped else "\n")
        + "- **Gating and calibration use one score.** An earlier version thresholded on Jev's\n"
        "  `confidence` while computing ECE on `p_chosen`; they differ on hundreds of rows.\n"
        "  Both now use `p_chosen`.\n"
        f"- **Rows come from {len(run['runs'])} invocations of `run_eval.py`.** Tasks were added one at a\n"
        "  time, so the table is not one run. Each row's receipts carry their own timestamps and the\n"
        "  site shows which invocation a row came from.\n"
        "- **Public gold.** Nine of eleven rows are academic benchmarks. Only CFPB routing uses\n"
        "  a live system's own labels, and those are chosen by the person filing, not an expert."
    )
    return blocks


def apply_blocks(text: str, blocks: dict) -> str:
    for name, body in blocks.items():
        open_tag, close_tag = GEN_OPEN.format(name=name), GEN_CLOSE.format(name=name)
        if open_tag not in text or close_tag not in text:
            raise SystemExit(f"README.md is missing the {name} generated block markers")
        head, rest = text.split(open_tag, 1)
        _, tail = rest.split(close_tag, 1)
        text = head + open_tag + "\n" + body + "\n" + close_tag + tail
    return text


def render_data_js(run, tasks, site, calls, curve) -> str:
    return (
        "// GENERATED by scripts/build_site.py from results/. Do not edit by hand.\n"
        "// Editorial text lives in site/copy.json; every number here comes from results/.\n"
        f"const SITE = {json.dumps(site, indent=2, ensure_ascii=False)};\n\n"
        f"const CALLS = {json.dumps(calls, indent=2, ensure_ascii=False)};\n\n"
        f"const COST_CURVE = {json.dumps(curve, indent=2, ensure_ascii=False)};\n\n"
        f"const RUN = {json.dumps(run, indent=2, ensure_ascii=False)};\n\n"
        f"const TASKS = {json.dumps(tasks, indent=2, ensure_ascii=False)};\n"
    )


def render_decision_page(t, run, site) -> str:
    slug = t["id"].replace("_", "-")
    url = f"{site['domain']}/decision/{slug}.html"
    # A verdict chip only ever compared Jev with 4o-mini. On the static page, which
    # is what crawlers and link previews read, say what else the data shows.
    notes = []
    if t["tfidf"]["vsJev"] == "tfidf":
        notes.append(f"A TF-IDF classifier trained on labelled data beats both APIs here "
                     f"at {pct(t['tfidf']['acc'])}. If you have labels, do not buy either.")
    if t.get("modern") and t["modern"]["vsJev"] == "modern":
        notes.append(f"{t['modern']['model']} beats Jev here at {pct(t['modern']['acc'])}.")
    if t["ece"]["ece"] > 0.12:
        notes.append(f"ECE {t['ece']['ece']}: do not quote the confidence as a probability.")
    caveats = ("<ul class=\"caveats\">" + "".join(f"<li>{e(n)}</li>" for n in notes) + "</ul>"
               if notes else "")

    # "Replace (ns)" said two opposite things at once. McNemar refusing to crown a
    # winner outranks the editorial verdict, exactly as the table shows it.
    if t["verdict"] == "neither":
        verdict = "Neither"
    elif t["ns"]:
        verdict = "ns"
    else:
        verdict = VERDICT_TEXT[t["verdict"]]
    ns_tag = ""
    # rows in the comparison table: Jev, 4o-mini, TF-IDF, plus the current model
    others = 2 + (1 if t.get("modern") else 0)
    title = f"{t['title']}: Jev vs {others} other models, measured | {site['name']}"
    desc = (
        f"{t['title']} on {t['dataset']}, n={t['n']} frozen gold. "
        f"Jev {pct(t['jev']['acc'])}, gpt-4o-mini {pct(t['mini']['acc'])}, "
        f"TF-IDF {pct(t['tfidf']['acc'])}. Verdict: {verdict}. ECE {t['ece']['ece']}."
    )
    gate = t["gates"].get("0.7", {})
    auto = t["autoSlice"]
    lift_pct = auto["lift"] * 100
    lift_txt = f"{'+' if lift_pct >= 0 else ''}{lift_pct:.1f}pt"
    jsonld = {
        "@context": "https://schema.org",
        "@type": "Dataset",
        "name": f"{t['title']} - cheap decision model bake-off",
        "description": desc,
        "url": url,
        "creator": {"@type": "Organization", "name": site["name"], "url": site["domain"]},
        "isBasedOn": t["dataset"],
        "dateModified": run["date"],
        "distribution": [{
            "@type": "DataDownload",
            "encodingFormat": "application/json",
            "contentUrl": f"{site['domain']}/receipts/{t['id']}.json",
        }],
        "variableMeasured": [
            {"@type": "PropertyValue", "name": "jev accuracy", "value": t["jev"]["acc"]},
            {"@type": "PropertyValue", "name": "gpt-4o-mini accuracy", "value": t["mini"]["acc"]},
            {"@type": "PropertyValue", "name": "tfidf accuracy", "value": t["tfidf"]["acc"]},
            {"@type": "PropertyValue", "name": "expected calibration error", "value": t["ece"]["ece"]},
        ],
    }
    train_n = f"{t['tfidf']['trainN']:,}"
    rows = [
        ("Jev " + run["modelJev"], pct(t["jev"]["acc"]),
         f"[{pct(t['jev']['lo'])} - {pct(t['jev']['hi'])}]",
         f"{t['jev']['p50']} ms", f"${t['jev']['perM']}"),
        (run["modelMini"], pct(t["mini"]["acc"]),
         f"[{pct(t['mini']['lo'])} - {pct(t['mini']['hi'])}]",
         f"{t['mini']['p50']} ms", f"${t['mini']['perM']}"),
        (f"TF-IDF + LR (train n={train_n})", pct(t["tfidf"]["acc"]),
         f"[{pct(t['tfidf']['lo'])} - {pct(t['tfidf']['hi'])}]",
         f"{t['tfidf']['meanUsBatched']} us mean per row, batched", "$0"),
    ]
    if t.get("modern"):
        m = t["modern"]
        # No published price was confirmed for this model, so the cost cell says so
        # rather than borrowing the column for a token count, which is a different unit.
        rows.insert(2, (m["model"], pct(m["acc"]),
                        f"[{pct(m['lo'])} - {pct(m['hi'])}]",
                        f"{m['p50']} ms",
                        f"unpriced ({m['tokens']} tok/call)"))
    tbody = "\n".join(
        "        <tr>" + "".join(f"<td>{e(c)}</td>" for c in r) + "</tr>" for r in rows
    )
    style = (
        "body{max-width:46rem;margin:0 auto;padding:2rem 1rem;"
        "font:15px/1.6 ui-sans-serif,system-ui,sans-serif;color:#18181b;background:#fafafa}"
        "table{border-collapse:collapse;width:100%;margin:1rem 0}"
        "th,td{border-bottom:1px solid #e4e4e7;padding:.5rem .6rem;text-align:left;"
        "font-variant-numeric:tabular-nums}"
        "th{font-size:11px;text-transform:uppercase;letter-spacing:.06em;color:#71717a}"
        "code{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:13px}"
        "pre{overflow-x:auto}"
        ".verdict{display:inline-block;border:1px solid #d4d4d8;border-radius:999px;"
        "padding:.1rem .6rem;font-size:12px}"
        ".scope{margin-left:.5rem;font-size:12px;color:#71717a}"
        ".stamp{margin-top:2rem;font:11px ui-monospace,monospace;color:#a1a1aa}"
        ".caveats{margin:.5rem 0 0;padding-left:1.1rem;color:#b45309;font-size:14px}"
        "a{color:#18181b}"
        "@media (prefers-color-scheme:dark){"
        "body{color:#e4e4e7;background:#09090b}th,td{border-color:#27272a}a{color:#e4e4e7}}"
    )
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{e(title)}</title>
<meta name="description" content="{e(desc)}">
<link rel="canonical" href="{e(url)}">
<link rel="icon" href="../favicon.svg" type="image/svg+xml">
<meta property="og:type" content="article">
<meta property="og:title" content="{e(title)}">
<meta property="og:description" content="{e(desc)}">
<meta property="og:url" content="{e(url)}">
<meta name="twitter:card" content="summary">
<meta name="whichjudge-build" content="{e(run['dataVersion'])}">
<script type="application/ld+json">{json.dumps(jsonld, ensure_ascii=False)}</script>
<style>{style}</style>
</head>
<body>
<p><a href="../index.html">{e(site['name'])}</a> / decision</p>
<h1>{e(t['title'])}</h1>
<p><span class="verdict">{e(verdict)}{ns_tag}</span>
<span class="scope">compares Jev with 4o-mini only</span></p>
{caveats}
<p>{e(t['why'])}</p>
<p><strong>Replaces:</strong> {e(t['replaces'])}<br>
<strong>Gold:</strong> <a href="{e(t['sourceUrl'])}" rel="noopener">{e(t['sourceName'])}</a>
{' via <a href="' + e(t['mirrorUrl']) + '" rel="noopener">a CC0 mirror</a>' if t.get('mirrorUrl') else ''}
- {e(t['dataset'])}, n={t['n']}, seed={run['seed']}<br>
<strong>Labels:</strong> <code>{e(t['labels'])}</code></p>
<table>
  <thead><tr><th>Model</th><th>Accuracy</th><th>95% CI</th><th>Latency (p50 unless stated)</th><th>Cost per 1M decisions</th></tr></thead>
  <tbody>
{tbody}
  </tbody>
</table>
<p><strong>McNemar Jev vs Mini:</strong> {e(t['mcnemar']['winner'])}, p={e(t['mcnemar']['p'])}
({t['mcnemar']['b']} Jev-only correct, {t['mcnemar']['c']} Mini-only correct).
<strong>TF-IDF vs Jev:</strong> {e(t['tfidf']['vsJev'])}.</p>
<h2>Quit line</h2>
<p>{e(t['gate'])}</p>
<p><strong>Auto slice:</strong> at Jev confidence &ge; {auto['gate']},
{pct(auto['acc'])} accurate on {pct(auto['cov'])} of traffic, which is
{lift_txt} against {pct(t['jev']['acc'])} ungated. That threshold is the strongest
one still covering at least half the traffic, picked by rule from the measured gates.</p>
<p><strong>Calibration:</strong> ECE {t['ece']['ece']} (max bin gap {t['ece']['mce']}).
ECE says whether the confidence can be read as a probability. It does not say whether
gating helps: thresholding only needs the model to rank its own answers, so a badly
calibrated task can still gate well. High ECE costs you the right to quote the number,
not the right to threshold on it.</p>
<h2>Verify this</h2>
<p>Frozen samples <code>{e(t['samplesSha'])}</code>, schema <code>{e(t['schemaSha'])}</code>.
Every call is stored with its request, response and SHA-256 in
<a href="../receipts/{e(t['id'])}.json">receipts/{e(t['id'])}.json</a>.</p>
<pre><code>git clone {e(site['repo'])}
python3 scripts/verify_run.py   # recounts this table from the receipts, no API key
python3 scripts/run_eval.py     # hits the APIs again with your own keys</code></pre>
<p>Independent bench, not affiliated with TypeSafe AI. Public gold labels, n={t['n']},
not a procurement study. <a href="../index.html">All {run['tasks']} decisions</a> &middot;
<a href="{e(site['repo'])}">source and data</a> &middot;
<a href="mailto:{e(site['contact'])}">{e(site['contact'])}</a></p>
<p class="stamp">build {e(run['dataVersion'])} &middot; this row from run {t['run']['index']} of {t['run']['of']}, {e(t['run']['start'][:16])}Z</p>
</body>
</html>
"""


def render_sitemap(tasks, site, run) -> str:
    urls = [f"{site['domain']}/", f"{site['domain']}/terms.html", f"{site['domain']}/privacy.html"]
    urls += [f"{site['domain']}/decision/{t['id'].replace('_', '-')}.html" for t in tasks]
    body = "\n".join(
        f"  <url><loc>{u}</loc><lastmod>{run['date']}</lastmod></url>" for u in urls
    )
    return ('<?xml version="1.0" encoding="UTF-8"?>\n'
            '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
            f"{body}\n</urlset>\n")


def render_404(site, run, tasks) -> str:
    """GitHub serves its own generic 404 otherwise, which reads as a dead project."""
    links = "\n".join(
        f'    <li><a href="/decision/{t["id"].replace("_", "-")}.html">{e(t["title"])}</a></li>'
        for t in tasks)
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Not found - {e(site['name'])}</title>
<meta name="robots" content="noindex">
<link rel="icon" href="/favicon.svg" type="image/svg+xml">
<style>
body{{max-width:44rem;margin:0 auto;padding:3rem 1rem;font:15px/1.6 ui-sans-serif,system-ui,sans-serif;color:#18181b;background:#fafafa}}
h1{{font-size:1.5rem;margin:0 0 .5rem}}
ul{{padding-left:1.1rem}}
li{{margin:.15rem 0}}
a{{color:#18181b}}
.muted{{color:#71717a;font-size:13px}}
@media (prefers-color-scheme:dark){{body{{color:#e4e4e7;background:#09090b}}a{{color:#e4e4e7}}}}
</style>
</head>
<body>
<h1>That page does not exist</h1>
<p>Nothing is broken; this URL just is not one of ours. The bench has
{run['tasks']} decisions, each on its own page:</p>
<ul>
{links}
</ul>
<p><a href="/">All {run['tasks']} decisions in one table</a> &middot;
<a href="{e(site['repo'])}">Source and data</a></p>
<p class="muted">Independent bench. Not affiliated with TypeSafe AI.</p>
</body>
</html>
"""


def render_robots(site) -> str:
    return f"User-agent: *\nAllow: /\n\nSitemap: {site['domain']}/sitemap.xml\n"


def render_index_meta(site, run, tasks) -> str:
    desc = site["description"]
    jsonld = {
        "@context": "https://schema.org",
        "@type": "Dataset",
        "name": f"{site['name']} - cheap decision model bake-off",
        "description": desc,
        "url": site["domain"] + "/",
        "creator": {"@type": "Organization", "name": site["name"], "url": site["domain"]},
        "dateModified": run["date"],
        "measurementTechnique": "Wilson 95% CI, McNemar paired test, expected calibration error",
        "hasPart": [
            {"@type": "Dataset",
             "name": t["title"],
             "url": f"{site['domain']}/decision/{t['id'].replace('_', '-')}.html"}
            for t in tasks
        ],
    }
    return "\n".join([
        META_START,
        '  <link rel="icon" href="/favicon.svg" type="image/svg+xml">',
        f'  <meta name="description" content="{e(desc)}">',
        f'  <link rel="canonical" href="{e(site["domain"])}/">',
        '  <meta property="og:type" content="website">',
        f'  <meta property="og:title" content="{e(site["name"])} - {e(site["tagline"])}">',
        f'  <meta property="og:description" content="{e(desc)}">',
        f'  <meta property="og:url" content="{e(site["domain"])}/">',
        '  <meta name="twitter:card" content="summary">',
        # The same stamp the decision pages carry. The homepage went without one
        # while the site claimed every page had it.
        f'  <meta name="whichjudge-build" content="{e(run["dataVersion"])}">',
        f'  <script type="application/ld+json">{json.dumps(jsonld, ensure_ascii=False)}</script>',
        "  " + META_END,
    ])


def write(path: Path, content: str, check: bool, drift: list) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    current = path.read_text(encoding="utf-8") if path.exists() else None
    if current == content:
        return
    rel = path.relative_to(ROOT).as_posix()
    if check:
        drift.append(rel)
    else:
        # Always LF: a Windows build and a Linux build must produce identical bytes,
        # otherwise --check flags drift on every platform switch.
        path.write_text(content, encoding="utf-8", newline="\n")
        print("wrote", rel)


def main() -> None:
    check = "--check" in sys.argv
    copy = load(SITE / "copy.json")
    site = copy["site"]
    summary = load(RESULTS / "summary.json")
    calib = load(RESULTS / "calibration.json")
    tfidf = load(RESULTS / "tfidf_baseline_summary.json")
    errors = load(RESULTS / "error_profile.json")
    gatefile = load(RESULTS / "gates.json")
    modern_path = RESULTS / "modern_baseline.json"
    modern = load(modern_path) if modern_path.exists() else None
    manifest = load(RESULTS / "manifest.json")
    curve_path = RESULTS / "cost_curve.json"
    curve = load(curve_path) if curve_path.exists() else None

    runs, windows = run_windows(summary)
    tasks = build_tasks(copy, summary, calib, tfidf, errors, modern, gatefile, windows)
    # Tasks may differ in size. Prompt injection only has 662 rows in existence, so
    # freezing 500 would leave nothing to train the classical baseline on. The site
    # shows each task's own n instead of claiming one number for all of them.
    sizes = sorted({row["n"] for row in summary})
    counts = {}
    for row in summary:
        counts[row["n"]] = counts.get(row["n"], 0) + 1
    n = max(counts, key=counts.get)

    # A fingerprint of everything that shapes the rendered site. Stamped on every
    # page and appended to the script URLs, so a reader can see which generation a
    # CDN edge handed them, and a new page can never run against a cached old script.
    # Built from content, not the git SHA, so --check stays stable across commits
    # that do not touch the site.
    fingerprint = hashlib.sha256()
    for part in ("summary.json", "calibration.json", "gates.json", "error_profile.json",
                 "tfidf_baseline_summary.json", "modern_baseline.json", "cost_curve.json"):
        f = RESULTS / part
        if f.exists():
            fingerprint.update(f.read_bytes())
    for part in ("copy.json", "app.js", "styles.css"):
        fingerprint.update((SITE / part).read_bytes())
    data_version = fingerprint.hexdigest()[:10]

    # Rows come from several invocations of run_eval.py (tasks were added one at a
    # time). The receipts' own timestamps say which; summary.json's run_id field
    # only exists on rows written after it was introduced and would under-count.
    run = {
        "date": manifest["finished_utc"][:10],
        "runId": manifest["run_id"],
        "runs": runs,
        "runIds": [r["start"] for r in runs],
        "dataVersion": data_version,
        "modelJev": "jev-1.13.0",
        "modelMini": "gpt-4o-mini-2024-07-18",
        "n": n,
        "nMin": sizes[0],
        "nMax": sizes[-1],
        "seed": manifest["seed"],
        "tasks": len(tasks),
        "note": (f"Frozen samples (seed={manifest['seed']}, n={sizes[0]}-{sizes[-1]} per task). "
                 "Wilson 95% CI on accuracy. "
                 "McNemar on paired errors. Full receipts in results/receipts/. "
                 "APIs do not sign responses."),
    }

    modern_name = next((t["modern"]["model"] for t in tasks if t.get("modern")), None)
    site["description"] = site["descriptionTemplate"].format(
        tasks=len(tasks), modern=modern_name or "no current model column",
        nmin=sizes[0], nmax=sizes[-1])

    drift: list = []
    write(SITE / "data.js", render_data_js(run, tasks, site, copy["calls"], curve), check, drift)
    for t in tasks:
        slug = t["id"].replace("_", "-")
        write(SITE / "decision" / f"{slug}.html", render_decision_page(t, run, site), check, drift)
    write(SITE / "sitemap.xml", render_sitemap(tasks, site, run), check, drift)
    readme = ROOT / "README.md"
    write(readme, apply_blocks(readme.read_text(encoding="utf-8"),
                               readme_blocks(tasks, run, curve, errors, gatefile, modern)),
          check, drift)
    write(SITE / "robots.txt", render_robots(site), check, drift)
    write(SITE / "404.html", render_404(site, run, tasks), check, drift)

    index = SITE / "index.html"
    src = index.read_text(encoding="utf-8")
    if META_START in src and META_END in src:
        head, rest = src.split(META_START, 1)
        _, tail = rest.split(META_END, 1)
        page = head + render_index_meta(site, run, tasks) + tail
        # Version the scripts with the fingerprint so the shell and its JS always
        # come from the same generation, whatever an edge has cached.
        page = re.sub(r'src="data\.js(?:\?v=[0-9a-f]+)?"', f'src="data.js?v={data_version}"', page)
        page = re.sub(r'src="app\.js(?:\?v=[0-9a-f]+)?"', f'src="app.js?v={data_version}"', page)
        write(index, page, check, drift)
    else:
        print("WARN index.html has no meta markers; skipping meta injection")

    if check and drift:
        print("STALE, these files disagree with results/:")
        for d in drift:
            print("  ", d)
        print("Run: python3 scripts/build_site.py")
        raise SystemExit(1)
    print("site is in sync with results/" if check else "build complete")


if __name__ == "__main__":
    main()
